export const GET_ALL_PROJECT_BEGIN = "GET_ALL_PROJECT_BEGIN";
export const GET_ALL_PROJECT_SUCCESS = "GET_ALL_PROJECT_SUCCESS";
export const GET_ALL_PROJECT_ERROR = "GET_ALL_PROJECT_ERROR";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";

export const USER_LOGIN_BEGIN = "USER_LOGIN_BEGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const CLEAR_ALERT = "CLEAR_ALERT";

export const PJ_CREATE_BEGIN = "PJ_CREATE_BEGIN";
export const PJ_CREATE_SUCCESS = "PJ_CREATE_SUCCESS";
export const PJ_CREATE_ERROR = "PJ_CREATE_ERROR";
